### ISSUE TITLE
Kafka Connect error while running docker-compose

### ISSUE THREAD

**Issue by ChaitanyaMM** [ivangfr/springboot-kafka-connect-jdbc-streams#3]
Hi ivan, firstly thank you for your effort here i would like to understand why the kafka connect im getting below error after docker-compose up -d

Traceback (most recent call last):
  File "/home/chaitanya/.local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/home/chaitanya/.local/lib/python2.7/site-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/home/chaitanya/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/chaitanya/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/chaitanya/.local/lib/python2.7/site-packages/docker/api/client.py", line 5, in <module>
    import requests
  File "/home/chaitanya/.local/lib/python2.7/site-packages/requests/__init__.py", line 113, in <module>
    from . import packages
  File "/home/chaitanya/.local/lib/python2.7/site-packages/requests/packages.py", line 7, in <module>
    locals()[package] = __import__(package)
ImportError: No module named idna

**Comment by ivangfr** [comment]
Hi @ChaitanyaMM I've rerun the `docker-compose up -d` of this project in my machine and I have `kafka-connect` up and running. Btw, what is the OS you are using?

**Comment by ivangfr** [comment]
Hey @ChaitanyaMM , as I haven't heard from you, I suppose you have found how to solve the issue with Kafka Connect. So, I am closing this issue.
